/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bakery;

import javax.swing.table.DefaultTableModel;
//import ketchupproduction.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.CallableStatement;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javafx.scene.control.DatePicker;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Mirik
 */
public class Payments_ex extends javax.swing.JFrame {
    Connection conn = null;
    Statement st = null;
    ResultSet rs = null;
    String id_buyer = "";
    boolean customizeWpnTable = false;
    boolean customizeAccountTable = false;
    boolean customizeDocumentTable = false;
    boolean customizeOrderTable = false;

    CallableStatement stored_pro = null;
    
    private void UpdateBudjet(){
        try{
            conn = ConnectMsSql.ConnectDB();

            String insert = "SELECT Kolichestvo_deneg_v_budgete FROM Budget";
            PreparedStatement pst = conn.prepareStatement(insert);
            ResultSet res = pst.executeQuery();
            st = conn.createStatement();
            res = st.executeQuery(insert);
             while(res.next()){
               
                 BudjetTxt.setText(String.format("%.2f", res.getFloat("Kolichestvo_deneg_v_budgete")));
             }

            conn.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void GetEmloyee(){
//        try{
//            conn = ConnectMsSql.ConnectDB();
//            //String query = "SELECT full_name FROM Employees WHERE login=" + KetchupProduction.id;
//           // PreparedStatement pst = conn.prepareStatement(query);
//           // rs = pst.executeQuery(); 
//
//            while(rs.next()){
//                BuhNameTxt.setText(rs.getString("Name"));
//            }
//
//            conn.close();
//        }
//        catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }
    }
    
    private void UpdateJTable(){
        
       
    }
    
    void DefaultValues(){
        LocalDate date = LocalDate.now(); // получаем текущую дату
        int year = date.getYear();
        
       // YearTxt.setText(String.valueOf(year));
       
        SimpleDateFormat formatter = new SimpleDateFormat("dd.MM.yyyy");  
        Date pickerDate = new Date(); 
        JDatePicker.setDate(pickerDate);
        
        conn = ConnectMsSql.ConnectDB();
       // String sql = "SELECT full_name FROM employees WHERE id ='"+KetchupProduction.id+"'";
        try 
        {
            st = conn.createStatement();
           // ResultSet rs = st.executeQuery(sql);
            while (rs.next()) 
            {
                BuhNameTxt.setText(rs.getString(1));
            }
            //MonthComboBox.setSelectedIndex(-1);
        } 
        catch (Exception e) 
        { 
            e.printStackTrace();
        }
 
    }
    
    
    void ComboboxMonth() {
        conn = ConnectMsSql.ConnectDB();
        String sql = "SELECT name FROM month";
        try {
            st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
        while (rs.next()) 
        {
            //MonthComboBox.addItem(rs.getString(1));
            
        }
           // MonthComboBox.setSelectedIndex(-1);
        } 
        catch (Exception e) { 
            e.printStackTrace();
        }
    }
    /**
     * Creates new form client_main_form
     */
    public Payments_ex() {
        initComponents();
        UpdateBudjet();
        GetEmloyee();
        ComboboxPos();
        ComboboxMonth();
        DefaultValues();
        //UpdateJTable();
       // setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("tomato-sauce.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        statusBar = new javax.swing.JLabel();
        wpnTableborder = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JDatePicker = new org.jdesktop.swingx.JXDatePicker();
        PosComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EmpComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();
        PaySumTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BudjetTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BuhNameTxt = new javax.swing.JTextField();
        PayBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Личный кабинет");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        desktopPane.setBackground(new java.awt.Color(51, 51, 51));
        desktopPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        statusBar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        statusBar.setForeground(new java.awt.Color(255, 0, 0));
        statusBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        desktopPane.add(statusBar);
        statusBar.setBounds(0, 620, 1040, 20);

        wpnTableborder.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Начисление зарплаты", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        wpnTableborder.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        wpnTableborder.setOpaque(false);

        jLabel3.setText("Календарь");

        JDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JDatePickerActionPerformed(evt);
            }
        });

        PosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Сотрудник");

        jLabel6.setText("Премия");

        EmpComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpComboBoxActionPerformed(evt);
            }
        });

        EmployeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(EmployeeTable);

        jLabel8.setText("Бюджет");

        jLabel9.setText("Должность");

        jLabel11.setText("Дата");

        PayBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PayBtn.setText("Выплатить");
        PayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wpnTableborderLayout = new javax.swing.GroupLayout(wpnTableborder);
        wpnTableborder.setLayout(wpnTableborderLayout);
        wpnTableborderLayout.setHorizontalGroup(
            wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wpnTableborderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(wpnTableborderLayout.createSequentialGroup()
                        .addGroup(wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(wpnTableborderLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel11)
                                .addGap(35, 35, 35)
                                .addComponent(BuhNameTxt))
                            .addGroup(wpnTableborderLayout.createSequentialGroup()
                                .addGroup(wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(wpnTableborderLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel9))
                                .addGap(49, 49, 49)
                                .addGroup(wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PaySumTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EmpComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(wpnTableborderLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(wpnTableborderLayout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BudjetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))))
                .addContainerGap())
        );
        wpnTableborderLayout.setVerticalGroup(
            wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wpnTableborderLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(BudjetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(PosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wpnTableborderLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(PayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(wpnTableborderLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PaySumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(BuhNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addGap(71, 71, 71))
        );

        desktopPane.add(wpnTableborder);
        wpnTableborder.setBounds(10, 0, 1010, 550);

        background.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        background.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bakery/7badce0e-43e6-4890-a2c1-dc414048b270.jpg"))); // NOI18N
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        desktopPane.add(background);
        background.setBounds(0, 0, 1040, 620);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bakery/.11111aaaa.png"))); // NOI18N
        jMenu1.setText("Таблицы");

        jMenuItem1.setText("Должность");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenu4.setText("Банк");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu4);

        jMenu6.setText("Сотрудники");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

//        new Main1().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void PayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayBtnActionPerformed
        // TODO add your handling code here:
    try {
            conn = ConnectMsSql.ConnectDB();
            Statement st = conn.createStatement();
            String test = EmpComboBox.getSelectedItem().toString();
            double amount = Double.parseDouble(PaySumTxt.getText());
String date=BuhNameTxt.getText();
// phone=JDatePicker.getText();
            int idProduct = 0;
            ResultSet id = st.executeQuery("select ID from Employees where Name = '" + test + "'");
            while (id.next()) {
                idProduct = Integer.parseInt(id.getString("ID"));
            }


            String dobavlenie = "INSERT INTO payments_to_emp (FK_Employer, Additional_Pay, Paymant_Date) VALUES(?,?,?)";
            PreparedStatement pst = conn.prepareStatement(dobavlenie);
            pst.setInt(1, idProduct);
            pst.setDouble(2, amount);
            pst.setString(3, date);

            JOptionPane.showMessageDialog(null, "Данные успешно добавленны.");
            pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        /*Регистрация гражданина в БД*/
        
        
    }//GEN-LAST:event_PayBtnActionPerformed

    private void EmployeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeTableMouseClicked
        // TODO add your handling code here:
          try{
            conn = ConnectMsSql.ConnectDB();
             
//            int row = jTable1.getSelectedRow();
//            String name = (jTable1.getModel().getValueAt(row,0).toString());

            int i=EmployeeTable.getSelectedRow();
        TableModel model=EmployeeTable.getModel();
//        NameTxt.setText(model.getValueAt(i,0).toString());
//        PositionTxt.setText(model.getValueAt(i,1).toString());
//        SalaryTxt.setText(model.getValueAt(i,2).toString());
//        adressTxt.setText(model.getValueAt(i,3).toString());
//        phoneTxt.setText(model.getValueAt(i,4).toString());
// phoneTxt1.setText(model.getValueAt(i,6).toString());
            
            
//            String sql = "SELECT Employees.Name,Position.Position as pos,Employees.Final_sallary, Employees.Address, Employees.Phone,Employees.Nadbavka FROM Employees INNER JOIN Position ON Employees.Position = Position.ID WHERE Employees.Name ='" + name + "'";
//            PreparedStatement pst=conn.prepareStatement(sql);
//            ResultSet rs = pst.executeQuery();
//            statement = conn.createStatement();
//            rs = statement.executeQuery(sql);
//            
//             while(rs.next()){
//                 NameTxt.setText(rs.getString("Name"));
//                 PositionTxt.setText(rs.getString("pos"));
//                 SalaryTxt.setText(rs.getString("Final_sallary"));
//                 adressTxt.setText(rs.getString("Address"));
//                phoneTxt.setText(rs.getString("Phone"));
//                phoneTxt1.setText(rs.getString("Nadbavka"));
//             }
        }
        catch(Exception e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_EmployeeTableMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        try{
        conn = ConnectMsSql.ConnectDB();
        //String sql = "SELECT Employees.Name,Position.Position as pos,Employees.Final_sallary, Employees.Address, Employees.Phone FROM Employees INNER JOIN Position ON Employees.Position = Position.ID WHERE Employees.Name ='" + name + "'";
            
        String sql = "SELECT\n" +
"     payments_to_emp.\"ID_salary\" AS payments_to_emp_ID_salary,\n" +
"     payments_to_emp.\"Amount_of_work\" AS payments_to_emp_Amount_of_work,\n" +
"     payments_to_emp.\"Sum_of_Bonus\" AS payments_to_emp_Sum_of_Bonus,\n" +
"     payments_to_emp.\"Salary\" AS payments_to_emp_Salary,\n" +
"     payments_to_emp.\"Total_salary\" AS payments_to_emp_Total_salary,\n" +
"     payments_to_emp.\"BuyStock_Amount\" AS payments_to_emp_BuyStock_Amount,\n" +
"     payments_to_emp.\"Manifacture_Amount\" AS payments_to_emp_Manifacture_Amount,\n" +
"     payments_to_emp.\"Sales_Amount\" AS payments_to_emp_Sales_Amount,\n" +
"     payments_to_emp.\"Paymant_Date\" AS payments_to_emp_Paymant_Date,\n" +
"     payments_to_emp.\"Additional_Pay\" AS payments_to_emp_Additional_Pay,\n" +
"     Employees.\"Name\" AS Employees_Name\n" +
"FROM\n" +
"     \"dbo\".\"Employees\" Employees INNER JOIN \"dbo\".\"payments_to_emp\" payments_to_emp ON Employees.\"ID\" = payments_to_emp.\"FK_Employer\"";
            Statement statement = conn.createStatement();
        rs = statement.executeQuery(sql);
        this.EmployeeTable.setModel(DbUtils.resultSetToTableModel(rs));
        EmployeeTable.getColumnModel().getColumn(0).setHeaderValue("Employees_Name");
        EmployeeTable.getColumnModel().getColumn(1).setHeaderValue("Amount_of_work");
        EmployeeTable.getColumnModel().getColumn(2).setHeaderValue("Sum_of_Bonus");
        EmployeeTable.getColumnModel().getColumn(3).setHeaderValue("Salary");
        EmployeeTable.getColumnModel().getColumn(4).setHeaderValue("Total_salary");
        EmployeeTable.getColumnModel().getColumn(5).setHeaderValue("BuyStock_Amount");
        EmployeeTable.getColumnModel().getColumn(6).setHeaderValue("Manifacture_Amount");
          EmployeeTable.getColumnModel().getColumn(7).setHeaderValue("Sales_Amount");
          EmployeeTable.getColumnModel().getColumn(8).setHeaderValue("Paymant_Date");
          EmployeeTable.getColumnModel().getColumn(9).setHeaderValue("Additional_Pay");
          conn.close();
        }
        
        catch(Exception e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void EmpComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpComboBoxActionPerformed

     void ComboboxPos() {
        conn = ConnectMsSql.ConnectDB();
        String sql = "SELECT Position FROM Position";
        try {
            st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
        while (rs.next()) 
        {
            PosComboBox.addItem(rs.getString(1));
            
        }
            PosComboBox.setSelectedIndex(-1);
        } 
        catch (Exception e) { 
            e.printStackTrace();
        }
    }
    
    private void PosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosComboBoxActionPerformed
        // TODO add your handling code here:
        EmpComboBox.removeAllItems();
        conn = ConnectMsSql.ConnectDB();
        try {

            String query = "SELECT ID FROM Position WHERE Position = '" + PosComboBox.getSelectedItem() + "'";
            PreparedStatement pst = conn.prepareStatement(query);
            rs = pst.executeQuery();
            int id_pos = 0;
            while(rs.next()){
                id_pos = rs.getInt("id");
            }

            String sql = "SELECT Name FROM Employees WHERE Position = '" + id_pos + "'";
            st = conn.createStatement();
            ResultSet res = st.executeQuery(sql);
            while (res.next())
            {
                EmpComboBox.addItem(res.getString(1));
            }
            EmpComboBox.setSelectedIndex(-1);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_PosComboBoxActionPerformed

    private void JDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JDatePickerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        positions field= new positions();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        cred field= new cred();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        employees field= new employees();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenu6MouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments_ex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments_ex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments_ex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments_ex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payments_ex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BudjetTxt;
    private javax.swing.JTextField BuhNameTxt;
    private javax.swing.JComboBox<String> EmpComboBox;
    private javax.swing.JTable EmployeeTable;
    private org.jdesktop.swingx.JXDatePicker JDatePicker;
    private javax.swing.JButton PayBtn;
    private javax.swing.JTextField PaySumTxt;
    private javax.swing.JComboBox<String> PosComboBox;
    private javax.swing.JLabel background;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel statusBar;
    private javax.swing.JPanel wpnTableborder;
    // End of variables declaration//GEN-END:variables

}
