/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bakery;


import javax.swing.table.DefaultTableModel;
//import ketchupproduction.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.CallableStatement;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javafx.scene.control.DatePicker;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


public class Payments extends javax.swing.JFrame {
    Connection conn = null;
    Statement st = null;
    ResultSet rs = null;
    String id_buyer = "";
    boolean customizeWpnTable = false;
    boolean customizeAccountTable = false;
    boolean customizeDocumentTable = false;
    boolean customizeOrderTable = false;

    CallableStatement stored_pro = null;
    
    private void UpdateBudjet(){
        try{
            conn = ConnectMsSql.ConnectDB();

            String insert = "SELECT Kolichestvo_deneg_v_budgete FROM Budget";
            PreparedStatement pst = conn.prepareStatement(insert);
            ResultSet res = pst.executeQuery();
            st = conn.createStatement();
            res = st.executeQuery(insert);
             while(res.next()){
               
                 BudjetTxt.setText(String.format("%.2f", res.getFloat("Kolichestvo_deneg_v_budgete")));
             }

            conn.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void GetEmloyee(){
        try{
            conn = ConnectMsSql.ConnectDB();
            //*String query = "SELECT full_name FROM Employees WHERE login=" + KetchupProduction.id;
           //* PreparedStatement pst = conn.prepareStatement(query);
           //* rs = pst.executeQuery(); 

            while(rs.next()){
                BuhNameTxt.setText(rs.getString("full_name"));
            }

            conn.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void UpdateJTable(){
        
        try{
            conn = ConnectMsSql.ConnectDB();

            stored_pro = conn.prepareCall("{call get_all_pay_employees }");
            rs = stored_pro.executeQuery();
            this.EmployeeTable.setModel(DbUtils.resultSetToTableModel(rs));
            stored_pro.execute();


        }        
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    void DefaultValues(){

        conn = ConnectMsSql.ConnectDB();
        //*String sql = "SELECT full_name FROM employees WHERE id ='"+KetchupProduction.id+"'";
        try 
        {
            st = conn.createStatement();
          //*  ResultSet rs = st.executeQuery(sql);
            while (rs.next()) 
            {
                BuhNameTxt.setText(rs.getString(1));
            }
            //MonthComboBox.setSelectedIndex(-1);
        } 
        catch (Exception e) 
        { 
            e.printStackTrace();
        }
 
    }
    

    /**
     * Creates new form client_main_form
     */
    public Payments() {
        initComponents();
        UpdateBudjet();
        GetEmloyee();

        DefaultValues();
        UpdateJTable();
       // setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("tomato-sauce.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        statusBar = new javax.swing.JLabel();
        wpnTableborder = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        BudjetTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BuhNameTxt = new javax.swing.JTextField();
        PayBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        miniMenu = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Личный кабинет");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        desktopPane.setBackground(new java.awt.Color(51, 51, 51));
        desktopPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        statusBar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        statusBar.setForeground(new java.awt.Color(255, 0, 0));
        statusBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        desktopPane.add(statusBar);
        statusBar.setBounds(0, 510, 730, 20);

        wpnTableborder.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Начисление зарплаты", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        wpnTableborder.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        wpnTableborder.setOpaque(false);

        jScrollPane1.setViewportView(EmployeeTable);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Бюджет");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Отвественный");

        PayBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PayBtn.setText("Выплатить");
        PayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wpnTableborderLayout = new javax.swing.GroupLayout(wpnTableborder);
        wpnTableborder.setLayout(wpnTableborderLayout);
        wpnTableborderLayout.setHorizontalGroup(
            wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wpnTableborderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(wpnTableborderLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BuhNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BudjetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wpnTableborderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );
        wpnTableborderLayout.setVerticalGroup(
            wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wpnTableborderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wpnTableborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(BuhNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(BudjetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        desktopPane.add(wpnTableborder);
        wpnTableborder.setBounds(10, 0, 700, 480);

        background.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        background.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bakery/7badce0e-43e6-4890-a2c1-dc414048b270.jpg"))); // NOI18N
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        desktopPane.add(background);
        background.setBounds(0, 0, 730, 510);

        menuBar.setBackground(new java.awt.Color(51, 51, 51));
        menuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        miniMenu.setForeground(new java.awt.Color(255, 255, 255));
        miniMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconspackage/menu_icon.png"))); // NOI18N
        miniMenu.setMnemonic('\u0438');
        miniMenu.setText("Мини-Меню");
        miniMenu.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        logoutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        logoutMenuItem.setBackground(new java.awt.Color(51, 51, 51));
        logoutMenuItem.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        logoutMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        logoutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconspackage/account_logout_icon.png"))); // NOI18N
        logoutMenuItem.setMnemonic('\u044b');
        logoutMenuItem.setText("Выйти");
        logoutMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMenuItemMousePressed(evt);
            }
        });
        miniMenu.add(logoutMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setBackground(new java.awt.Color(51, 51, 51));
        exitMenuItem.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        exitMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconspackage/exit_icon.png"))); // NOI18N
        exitMenuItem.setMnemonic('\u044b');
        exitMenuItem.setText("Выход");
        exitMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        miniMenu.add(exitMenuItem);

        menuBar.add(miniMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        new Main1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void PayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayBtnActionPerformed
        // TODO add your handling code here:
        try{
            conn = ConnectMsSql.ConnectDB();
            int answer = 0;
            String query = "DECLARE @res AS int EXEC @res = pay_salary ? SELECT @res";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setInt(1,1);
           
            rs = ps.executeQuery();
            while(rs.next()){
            answer = rs.getInt(1);
            }
            ps.close();
            
            switch (answer) {
                case 1:
                    statusBar.setText("Операция успешно выполнена!");
                    statusBar.setForeground(Color.green);
                    break;
                case 0:
                    statusBar.setText("Плата за этот месяц уже произведена!");
                    statusBar.setForeground(Color.red);
                    break;
                case 404:
                    statusBar.setText("Не хватает средств для выплаты зароботной платы!");
                    statusBar.setForeground(Color.red);
                    break;
                default:
                    break;
            }
        }        
        catch(Exception e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_PayBtnActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void logoutMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMenuItemMousePressed

        new Main1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMenuItemMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BudjetTxt;
    private javax.swing.JTextField BuhNameTxt;
    private javax.swing.JTable EmployeeTable;
    private javax.swing.JButton PayBtn;
    private javax.swing.JLabel background;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu miniMenu;
    private javax.swing.JLabel statusBar;
    private javax.swing.JPanel wpnTableborder;
    // End of variables declaration//GEN-END:variables

}
