/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dentist;

//import dori.jasper.engine.JasperCompileManager;
//import dori.jasper.engine.JasperFillManager;
//import dori.jasper.engine.JasperPrint;
//import dori.jasper.engine.JasperReport;
//import dori.jasper.engine.design.JRDesignQuery;
//import dori.jasper.engine.design.JasperDesign;
//import dori.jasper.engine.xml.JRXmlLoader;
//import dori.jasper.view.JasperViewer;
import mssqlconnection.*;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.*;
import static jdk.nashorn.internal.runtime.Debug.id;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Aidin
 */
public class Отчёт1 extends javax.swing.JInternalFrame {
Connection conn;
   	ResultSet rs = null;

    /**
     * Creates new form Отчёт
     */
    public Отчёт1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Ежедневный отчет");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Ежемесячный отчет");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Отчёт");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setText("отчет по id пациентов ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void showById(){
        try{
            conn = ConnectMsSql.ConnectDB();
            JasperDesign jasperDesign = JRXmlLoader.load("C:\\Users\\Aidin\\Documents\\3 курс\\Осенний семестр\\Клиент сервер\\MsSqlConnection\\src\\Dentist\\report4.jrxml");
            String sql = "SELECT\n" +
"     Appointment_Doctor.\"ID\" AS Appointment_Doctor_ID,\n" +
"     Appointment_Doctor.\"Дата\" AS Appointment_Doctor_Дата,\n" +
"     Appointment_Doctor.\"Цена_за_услугу\" AS Appointment_Doctor_Цена_за_услугу,\n" +
"     Appointment_Doctor.\"Посещение\" AS Appointment_Doctor_Посещение,\n" +
"     Table_client.\"ФИО\" AS Table_client_ФИО,\n" +
"     Table_diagnosis.\"Диагноз\" AS Table_diagnosis_Диагноз,\n" +
"     Table_doctor.\"ФИО\" AS Table_doctor_ФИО\n" +
"FROM\n" +
"     \"dbo\".\"Table_client\" Table_client INNER JOIN \"dbo\".\"Appointment_Doctor\" Appointment_Doctor ON Table_client.\"id\" = Appointment_Doctor.\"ФИО\"\n" +
"     INNER JOIN \"dbo\".\"Table_diagnosis\" Table_diagnosis ON Appointment_Doctor.\"Диагноз\" = Table_diagnosis.\"id\"\n" +
"     INNER JOIN \"dbo\".\"Table_doctor\" Table_doctor ON Appointment_Doctor.\"Леч_врач\" = Table_doctor.\"ID\"\n" +
"WHERE\n" +
"     Appointment_Doctor.\"Дата\" = DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE()),0)\n" +
" AND \n" +
"     Appointment_Doctor.\"Дата\" < DATEADD(MONTH,DATEDIFF(MONTH,0,GETDATE())+1,0)";
           JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jasperDesign.setQuery(newQuery);
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
            JasperViewer.viewReport(jasperPrint,false);          
        }
        catch(Exception e){
        e.printStackTrace();
        }
    }

    
     private void showBydate(){
        try{
             String perem = jTextField1.getText();
            conn = ConnectMsSql.ConnectDB();
            JasperDesign jasperDesign = JRXmlLoader.load("C:\\Users\\Aidin\\Documents\\3 курс\\Осенний семестр\\Клиент сервер\\MsSqlConnection\\src\\Dentist\\report4.jrxml");
            String sql = "SELECT\n" +
"     Appointment_Doctor.\"ID\" AS Appointment_Doctor_ID,\n" +
"     Appointment_Doctor.\"Дата\" AS Appointment_Doctor_Дата,\n" +
"     Appointment_Doctor.\"Цена_за_услугу\" AS Appointment_Doctor_Цена_за_услугу,\n" +
"     Appointment_Doctor.\"Посещение\" AS Appointment_Doctor_Посещение,\n" +
"     Table_client.\"ФИО\" AS Table_client_ФИО,\n" +
"     Table_diagnosis.\"Диагноз\" AS Table_diagnosis_Диагноз,\n" +
"     Table_doctor.\"ФИО\" AS Table_doctor_ФИО\n" +
"FROM\n" +
"     \"dbo\".\"Table_client\" Table_client INNER JOIN \"dbo\".\"Appointment_Doctor\" Appointment_Doctor ON Table_client.\"id\" = Appointment_Doctor.\"ФИО\"\n" +
"     INNER JOIN \"dbo\".\"Table_diagnosis\" Table_diagnosis ON Appointment_Doctor.\"Диагноз\" = Table_diagnosis.\"id\"\n" +
"     INNER JOIN \"dbo\".\"Table_doctor\" Table_doctor ON Appointment_Doctor.\"Леч_врач\" = Table_doctor.\"ID\"\n" +
"WHERE\n" +
"     Appointment_Doctor.\"ID\" = "+ perem;
           JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jasperDesign.setQuery(newQuery);
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
            JasperViewer.viewReport(jasperPrint,false);          
        }
        catch(Exception e){
        e.printStackTrace();
        }
    }
    
    
    
    private void showMeAllReport(){
        try{
            conn = ConnectMsSql.ConnectDB();
            JasperDesign jasperDesign = JRXmlLoader.load("C:\\Users\\Aidin\\Documents\\3 курс\\Осенний семестр\\Клиент сервер\\MsSqlConnection\\src\\Dentist\\report4.jrxml"); 
// String sql = "SELECT\n" +
//"     Appointment_Doctor.\"ID\" AS Appointment_Doctor_ID,\n" +
//"     Appointment_Doctor.\"Дата\" AS Appointment_Doctor_Дата,\n" +
//"     Appointment_Doctor.\"Цена_за_услугу\" AS Appointment_Doctor_Цена_за_услугу,\n" +
//"     Appointment_Doctor.\"Посещение\" AS Appointment_Doctor_Посещение,\n" +
//"     Table_doctor.\"ФИО\" AS Table_doctor_ФИО,\n" +
//"     Table_client.\"ФИО\" AS Table_client_ФИО,\n" +
//"     Table_diagnosis.\"Диагноз\" AS Table_diagnosis_Диагноз\n" +
//"FROM\n" +
//"     \"dbo\".\"Table_doctor\" Table_doctor INNER JOIN \"dbo\".\"Appointment_Doctor\" Appointment_Doctor ON Table_doctor.\"ID\" = Appointment_Doctor.\"Леч_врач\"\n" +
//"     INNER JOIN \"dbo\".\"Table_client\" Table_client ON Appointment_Doctor.\"ФИО\" = Table_client.\"id\"\n" +
//"     INNER JOIN \"dbo\".\"Table_diagnosis\" Table_diagnosis ON Appointment_Doctor.\"Диагноз\" = Table_diagnosis.\"id\"";
//            
String sql = "SELECT\n" +
"     Appointment_Doctor.\"ID\" AS Appointment_Doctor_ID,\n" +
"     Appointment_Doctor.\"Дата\" AS Appointment_Doctor_Дата,\n" +
"     Appointment_Doctor.\"Цена_за_услугу\" AS Appointment_Doctor_Цена_за_услугу,\n" +
"     Appointment_Doctor.\"Посещение\" AS Appointment_Doctor_Посещение,\n" +
"     Table_client.\"ФИО\" AS Table_client_ФИО,\n" +
"     Table_diagnosis.\"Диагноз\" AS Table_diagnosis_Диагноз,\n" +
"     Table_doctor.\"ФИО\" AS Table_doctor_ФИО\n" +
"FROM\n" +
"     \"dbo\".\"Table_client\" Table_client INNER JOIN \"dbo\".\"Appointment_Doctor\" Appointment_Doctor ON Table_client.\"id\" = Appointment_Doctor.\"ФИО\"\n" +
"     INNER JOIN \"dbo\".\"Table_diagnosis\" Table_diagnosis ON Appointment_Doctor.\"Диагноз\" = Table_diagnosis.\"id\"\n" +
"     INNER JOIN \"dbo\".\"Table_doctor\" Table_doctor ON Appointment_Doctor.\"Леч_врач\" = Table_doctor.\"ID\"\n" +
"WHERE\n" +
"     Appointment_Doctor.\"Дата\" >= DATEADD(day,DATEDIFF(day,0,GETDATE()),0)\n" +
" AND \n" +
"     Appointment_Doctor.\"Дата\" < DATEADD(day,DATEDIFF(day,0,GETDATE())+1,0)";
         JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jasperDesign.setQuery(newQuery);
            
           JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
            JasperViewer.viewReport(jasperPrint,false);
            
        }
        catch(Exception e){
        e.printStackTrace();
        }
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showMeAllReport();

        //InputStream i= getClass().getResourceAsStream("C:\\Users\\Aidin\\Documents\\3 курс\\осений семестр\\Клиент сервер\\MsSqlConnection\\src\\mssqlconnection\\report1.jrxml");
        //JasperPrint jp=JasperFillManager.fillReport;
        //       try{
            //            String report=("C:\\Users\\Aidin\\Documents\\3 курс\\осений семестр\\Клиент сервер\\MsSqlConnection\\src\\mssqlconnection\\report1.jrxml");
            //            JasperReport jr=JasperCompileManager.compileReport(report);
            //            JasperPrint jp=JasperFillManager.fillReport(jr,null,conn);
            //            JasperViewer.viewReport(jp);
            //        }
        //        catch(Exception e){
            //     JOptionPane.showConfirmDialog(null, e);
            //        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        showById();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        showBydate();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
